apiVersion: v1
kind: Service

metadata:
  name: thumbnail-service
  namespace: thumbnail-pipeline

spec:
  type: ClusterIP

  selector:
    app: thumbnail-service

  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
