apiVersion: v1
kind: Service

metadata:
  name: thumbnail-service
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "thumbnail-pipeline.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}

  selector:
    {{- include "thumbnail-pipeline.applicationSelectorLabels" . | nindent 4 }}

  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000