apiVersion: batch/v1
kind: Job

metadata:
  name: minio-init
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "thumbnail-pipeline.labels" . | nindent 4 }}

spec:
  backoffLimit: {{ .Values.minioInit.backoffLimit }}

  template:
    metadata:
      labels:
        app: minio-init

    spec:
      restartPolicy: OnFailure

      containers:
        - name: minio-init
          image: "{{ .Values.minioInit.image.repository }}:{{ .Values.minioInit.image.tag }}"

          command:
            - /bin/sh
            - -c
            - |
              until mc alias set local http://minio:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD"; do
                echo "Waiting for MinIO..."
                sleep 2
              done

              mc mb --ignore-existing local/thumbnail-pipeline

              echo "MinIO bucket initialization complete."

          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_USER

            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_PASSWORD