apiVersion: v1
kind: Secret

metadata:
  name: minio-secret
  namespace: "{{ .Release.Namespace }}"

type: Opaque

stringData:
  MINIO_ROOT_USER: "{{ .Values.secrets.minioRootUser }}"
  MINIO_ROOT_PASSWORD: "{{ .Values.secrets.minioRootPassword }}"
